// client-react/src/components/Home/CrudOperations/Users/Users.tsx
import React from 'react';
import 'components/Home/CrudOperations/Menu/Menu.scss';
import { UserData, UsersProps } from 'common/types';

function Users(props: UsersProps): JSX.Element {
	return (
		<div className="Users">
			<table className="table">
				<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
					<th>Username</th>
					<th>Website</th>
				</tr>
				</thead>
				<tbody>
				{props.users.map((user: UserData) => (
					<tr key={user.id}>
						<td data-testid="user-id">{user.id}</td>
						<td data-testid="user-name">{user.name}</td>
						<td data-testid="user-username">{user.username}</td>
						<td data-testid="user-website">{user.website}</td>
					</tr>
				))}
				</tbody>
			</table>
		</div>
	)
}

export default Users;

// client-angular/src/app/components/home/crud-operations/users/users.component.ts
import { Component, Input } from '@angular/core';
import { UserData } from 'src/app/shared/types';

@Component({
  selector: 'app-users',
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.scss']
})
export class UsersComponent {
  @Input() users?: UserData[];

  constructor() { }
}

<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Username</th>
    <th>Website</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let user of users">
    <td>{{user.id}}</td>
    <td>{{user.name}}</td>
    <td>{{user.username}}</td>
    <td>{{user.website}}</td>
  </tr>
  </tbody>
</table>
