// client-angular/src/app/components/home/file-upload/file-upload.component.ts
import { Component } from '@angular/core';
import { ApiService } from 'src/app/services/api/api.service';
import { FileUploadResponse } from 'src/app/shared/types';

@Component({
  selector: 'app-file-upload',
  templateUrl: './file-upload.component.html',
  styleUrls: ['./file-upload.component.scss']
})
export class FileUploadComponent {
  file?: File;
  fileName?: string;
  imageUrl?: string;

  constructor(private api: ApiService) { }

  handleFileUploadClick(event: any) {
    const file: File = event.target.files[0];

    if (!file) return;

    this.file = file;
    this.fileName = file.name;
  }

  uploadFile() {
    if (!this.file) return;

    const formData: FormData = new FormData();
    formData.append('file', this.file);

    this.api.uploadFile(formData).subscribe((data: FileUploadResponse) => {
      this.imageUrl = data.url;
    });
  }
}

<div class="file-upload-component">
  <h2 class="title">File Upload</h2>
  <label for="upload-input" class="button button-blue">
    Select file to upload
  </label>
  <input class="file-input" id="upload-input" type="file" (change)="handleFileUploadClick($event)">
  <h4 class="file-name">{{fileName}}</h4>
  <button class="button button-blue" *ngIf="fileName" (click)="uploadFile()">
    Upload file to server
  </button>
  <img alt="uploaded" class="uploaded-image" [src]="imageUrl" *ngIf="imageUrl">
</div>

// client-react/src/components/Home/FileUpload/FileUpload.tsx
import React, {useState} from 'react';
import axios from 'axios';
import 'components/Home/FileUpload/FileUpload.scss';

function FileUpload(): JSX.Element {
	const [file, setFile] = useState<File>();
	const [fileName, setFileName] = useState('');
	const [imageUrl, setImageUrl] = useState('');

	function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
		const file = e.target.files![0];
		setFile(e.target.files![0]);
		setFileName(file.name);
	}

	async function uploadFile(event: React.MouseEvent<HTMLButtonElement>): Promise<void> {
		event.preventDefault();
		try {
			if (!file) return;

			const data = new FormData();
			data.append('file', file);
			const response = await axios.post('/api/file/upload', data);
			setImageUrl(response.data.url);
		} catch (e) {
			console.log(e);
		}
	}

	return (
		<div className="FileUpload">
			<h2 className="title">File Upload</h2>
			<form className="form">
				<label htmlFor="upload-input" className="button button-blue">
					Select file to upload
				</label>
				<h4 className="file-name">{fileName}</h4>
				<input
					id="upload-input"
					data-testid="upload-input"
					style={{display: 'none'}}
					type="file"
					onChange={handleFileUpload} />
				{
					fileName.length > 0 &&
					<button
						data-testid="upload-button"
						className="button button-blue"
						onClick={uploadFile}>
						Upload file to server
					</button>
				}
				{
					imageUrl.length > 0 &&
					<img
						alt="uploaded"
						className="uploaded-image"
						data-testid="uploaded-image"
						src={imageUrl} />
				}
			</form>
		</div>
	);
}

export default FileUpload;
