// client-angular/src/app/components/home/crud-operations/menu/menu.component.ts
import { Component, Input } from '@angular/core';
import { DishData } from 'src/app/shared/types';
import { formatDate } from 'src/app/shared/utils';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent {
  @Input() menu?: DishData[];

  formatDate = formatDate;

  constructor() { }
}

<table class="table">
  <thead>
  <tr>
    <th>Dish ID</th>
    <th>Dish Creation Date</th>
    <th>Dish Name</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let dish of menu">
    <td>{{dish._id}}</td>
    <td>{{formatDate(dish.creation_date)}}</td>
    <td>{{dish.name}}</td>
  </tr>
  </tbody>
</table>

// client-react/src/components/Home/CrudOperations/Menu/Menu.tsx
import React from 'react';
import 'components/Home/CrudOperations/Menu/Menu.scss';
import {formatDate} from 'common/utils';
import {DishData, MenuProps} from 'common/types';

function Menu(props: MenuProps): JSX.Element {
	return (
		<div className="Menu">
			<table className="table">
				<thead>
				<tr>
					<th>Dish ID</th>
					<th>Dish Creation Date</th>
					<th>Dish Name</th>
				</tr>
				</thead>
				<tbody>
				{props.menu.map((item: DishData) => (
					<tr key={item._id}>
						<td data-testid="dish-id">{item._id}</td>
						<td data-testid="dish-date">{formatDate(item.creation_date)}</td>
						<td data-testid="dish-name">{item.name}</td>
					</tr>
				))}
				</tbody>
			</table>
		</div>
	)
}

export default Menu;
